version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-seguros
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_seguros
      MYSQL_USER: safebryan
      MYSQL_PASSWORD: 081012
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - seguros-net

volumes:
  mysql_data:

networks:
  seguros-net:
    driver: bridge