version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-seguros
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_seguros
      MYSQL_USER: safebryan
      MYSQL_PASSWORD: 081012
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - seguros-net

  backend:
    build:
      context: .
    container_name: backend-seguros
    ports:
      - "8080:8080"
    restart: always
    networks:
      - seguros-net
    depends_on:
      - mysql
    env_file:
      - .env


  frontend:
    build:
      context: ./frontGestion
    container_name: frontend-seguros
    ports:
      - "4200:8080"  # Puerto local 4200 -> puerto del contenedor 8080
    restart: always
    networks:
      - seguros-net
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  seguros-net:
    driver: bridge
